services:
  - type: web
    name: dvla-proxy
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DVLA_API_KEY
        sync: false
